# Altere a linha do tema para o 'minima'
theme: minima
title: "Database de Propostas Rag"
description: "ragnahow"

# Configuração correta de navegação para o tema Minima
header_pages:
  - index.md
  - insights.md
  - quest-items/quest-cards.md
  - quest-items/quest-monster-items.md
  - quest-items/quest-mvp-items.md
  - rops-quests/top/5529-satanic-bone-helm.md
